let players = [{name: "Du&#353;an",
			lastname: "Markovi&#263;",
			number: 26,
			position: "Goalkeeper",
			age: 23,
			image: "D-Markovic.png"},
			{name: "Danijel",
			lastname: "Mi&#263;anovi&#263;",
			number: 88,
			position: "Goalkeeper",
			age: 22,
			image: "D-Micanovic.png"},
			{name: "Marko",
			lastname: "Nikoli&#263;",
			number: 2,
			position: "Centre-back",
			age: 23,
			image: "M-Nikolic.png"},
			{name: "Milo&#353;",
			lastname: "Tanovi&#263;",
			number: 5,
			position: "Right-back",
			age: 25,
			image: "M-Tanovic.png"},
			{name: "Filip",
			lastname: "Kasalica",
			number: 9,
			position: "Left Winger",
			age: 33,
			image: "F-Kasalica.png"},
			{name: "Milo&#353;",
			lastname: "Trifunovi&#263;",
			number: 14,
			position: "Centre-forward",
			age: 37,
			image: "M-Trifunovic.png"},
			{name: "Aleksandar",
			lastname: "Busni&#263;",
			number: 22,
			position: "Central Midfield",
			age: 24,
			image: "A-Busnic.png"},
			{name: "Du&#353;an",
			lastname: "&#381ivkovi&#263;",
			number: 27,
			position: "Attacking Midfield",
			age: 25,
			image: "D-Zivkovic.png"},
			{name: "Veljko",
			lastname: "Trifunovi&#263;",
			number: 29,
			position: "Right Winger",
			age: 23,
			image: "V-Trifunovic.png"},
			{name: "Vanja",
			lastname: "Ili&#263;",
			number: 55,
			position: "Right Winger",
			age: 22,
			image: "V-Ilic.png"},
			{name: "Andrija",
			lastname: "Kaludjerovi&#263;",
			number: 99,
			position: "Centre-forward",
			age: 34,
			image: "A-Kaludjerovic.png"},
			{name: "Uro&#353;",
			lastname: "Damjanovi&#263;",
			number: 8,
			position: "Attacking Midfield",
			age: 26,
			image: "U-Damjanovic.png"},
			{name: "Ostoja",
			lastname: "Stjepanovi&#263;",
			number: 17,
			position: "Defensive Midfield",
			age: 36,
			image: "O-Stjepanovic.png"},
			{name: "Nemanja",
			lastname: "Petrovi&#263;",
			number: 18,
			position: "Left-Back",
			age: 29,
			image: "N-Petrovic.png"},
			{name: "Milan",
			lastname: "Perendija",
			number: 7,
			position: "Centre-back",
			age: 35,
			image: "M-Perendija.png"}]

const fcRad = {team: "FK Rad",
			logo: "./images/fc-rad.png",
			playersList: players}